apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: front-end
  endpoints:
  - port: tcp-4040
  namespaceSelector:
    matchNames:
    - default