apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: app
          image: yukselburak/app:v1.6
          env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          - name: MONGO_INITDB_DATABASE
            value: admin
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---
kind: Service
apiVersion: v1
metadata:
  name: api-app
  labels:
      app: api-app
spec:
  selector:
    app: api-app
  type: ClusterIP
  ports:
  - name: tcp-80
    protocol: TCP
    port: 80
    targetPort: 5000

