apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end-pod-start
  name: front-end-pod-start
spec:
  containers:
  - name: front-end-container
    image: nginx:1.20
    ports:
    - containerPort: 80
      name: http-port
    livenessProbe:
      httpGet:
        path: /
        port: http-port
      failureThreshold: 1
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /
        port: http-port
      failureThreshold: 30
      periodSeconds: 10