apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end-pod-tcp
  name: front-end-pod-tcp
spec:
  containers:
  - name: front-end-container
    image: nginx:1.20
    ports:
    - containerPort: 80
      name: http
    readinessProbe:
      tcpSocket:
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: http
      initialDelaySeconds: 15
      periodSeconds: 20
    
