apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end-pod-http
  name: front-end-pod-http
spec:
  containers:
  - name: front-end-container
    image: nginx:1.20
    ports:
    - containerPort: 80
      name: http
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    
