apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-end-service
  name: front-end-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front-end-pod
  type: ClusterIP
