apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front-end-pod
  name: front-end-pod
spec:
  containers:
  - name: front-end-container
    image: nginx:1.20
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: front-end-cm-ref
      mountPath: /usr/share/nginx/html
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: front-end-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: front-end-secret
          key: password
  volumes:
    - name: front-end-cm-ref
      configMap:
        name: front-end-cm
    
