apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-frontend
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup my-nginxx.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for frontend; sleep 2; done"]
  - name: init-redis-follower
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup my-nginx-2.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis-follower; sleep 2; done"]