apiVersion: v1
kind: Pod
metadata:
  name: broken-pod-1
spec:
  volumes:
    - name: not-exist-volume
      persistentVolumeClaim:
        claimName: not-exist-claim
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: broken-container
      volumeMounts:
        - mountPath: "/not/exist"
          name: not-exist-volume