apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-2
spec:
  selector:
    matchLabels:
      app: deploy-2
  replicas: 2
  template:
    metadata:
      labels:
        app: deploy-2
    spec:
      containers:
      - name: deploy-2
        image: nginx
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20