apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deploy-def
  labels:
    app: front-end-deploy-def
spec:
  replicas: 4
  selector:
    matchLabels:
      app: front-end-deploy-pod
  template:
    metadata:
      labels:
        app: front-end-deploy-pod
    spec:
      containers:
      - name: front-end-deploy-container
        image: nginx:1.20
        ports:
        - containerPort: 80