apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-app
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: api-app
  endpoints:
  - port: tcp-80
  namespaceSelector:
    matchNames:
    - default
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db-app
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: mongo-db
  endpoints:
  - port: tcp-9216
  namespaceSelector:
    matchNames:
    - default