apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: app
    role: alert-rules
    release: kube-prom-stack
  name: prometheus-example-rules
  namespace: monitoring
spec:
  groups:
  - name: example
    rules:
      - alert: KubernetesPodNotHealthy
        expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for longer than 15 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  - name: ConnectionThresholdMonitoring
    rules:
    - alert: HighConnectionCount
      expr: sum(flask_http_request_total) by (pod) > 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High Connection Count in Pods"
        description: "The sum of network receive errors for pods is above the threshold (10) for the last 5 minutes."

