apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: kube-prom-stack
  name: custom-rules
  namespace: monitoring
spec:
  groups:
    - name: not-ready-mongodb
      rules:
        - alert: PodNotReady
          expr: kube_statefulset_status_replicas_ready{namespace="default", statefulset="mongo-db"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is NotReady"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has transitioned to a NotReady state."
    - name: not-ready-app
      rules:
        - alert: PodNotReady
          expr: kube_deployment_status_replicas_ready{namespace="default", deployment="api-app"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is NotReady"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has transitioned to a NotReady state."
    - name: any-pod-not-running
      rules:
        - alert: PodNotReady
          expr: kube_pod_status_phase{phase="Running", namespace="default"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is NotReady"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has transitioned to a NotReady state."
