apiVersion: v1
data:
  config.hcl: |
    listen {
      port = 9216
    }
    namespace "mongodb" {
      source = {
        syslog {
          listen_address = "udp://127.0.0.1:5531"
          format = "rfc3164"
          tags = ["mongodb"]
        }
      }
      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
      labels {
        app = "default"
      }
    }
kind: ConfigMap
metadata:
  name: exporter-config
