apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app.kubernetes.io/component: mongo-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: tcp-27017
    - port: 9216
      targetPort: 9216
      protocol: TCP
      name: tcp-prom-exporter
  clusterIP: None
  selector:
    app: mongo-db
